apiVersion: v1
kind: Pod
metadata:
  name: zlink
  labels:
    app: zlink-short
spec:
  containers:
  - name: zlink-container
    image: sakibcoolz/zlink_service
    env:
    - name:  "SERVICEHOST"
      value: "localhost"
    - name: "VERSION"
      value: "sakib"
    - name: "SERVICEPORT"
      value: "5000"
